version: '2.2'

services:

  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    environment:
      MONGO_INTITD_ROOT_USERNAME: root
      MONGO_INTIDB_ROOT_PASSWORD: test123

  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGO_INTITD_ROOT_USERNAME: root
      ME_MONGO_INTITD_ROOT_USERNAME: test123
      ME_CONFIG_MONGODB_URL: mongodb://root:test123@mongo:27017/
